SignUp_btn = 'css:.d-flex.justify-content-center.links > a'
firstName_txtField = 'id:firstName'
lastName_txtField = 'id:lastName'
email_txtField = 'id:emailaddress'
phoneNumber_txtField = 'id:phoneNumber'
password_txtField = 'id:password'
confirmPassword_txtField = 'id:password_confirmation'
button = 'css:.btn-primary'
alert = 'class:.alert'
sup_Profile = 'css:[data-role="supplier"]'
SignIn_btn = 'css:strong'
